### ISSUE TITLE
python implementation

### ISSUE THREAD

**Issue by ghost** [SeungjunNah/DeepDeblur_release#11]
Hi , do you know if there is an implementation in python for your code?
Thanks!

**Comment by SeungjunNah** [comment]
As far as I know, there's no python implementation for our project.
Currently, I don't have any plans for python implementation.
However, the implementation shouldn't be difficult if you are used to any of python deep learning frameworks such as caffe, tensorflow, pytorch, etc.

**Comment by ghost** [comment]
Hi thanks for the answer!
The paper is a little different from the code and i am not familiar with
lua.. do you have any advice for how to implement this in python?
Thanks!
Sivan

בתאריך 3 בנוב׳ 2017 06:39 PM,‏ "Seungjun Nah" <notifications@github.com>
כתב:

**Comment by SeungjunNah** [comment]
As our code is based on torch, I guess implementing in pytorch could have minimal difference, if you are not familiar with other frameworks.

**Comment by ghost** [comment]
My plan is actually to use tensorflow . Do you have anywhere maybe a list
with the changes between the paper and the code ? For some of us who dont
understand lua :)
Thanks!

בתאריך 3 בנוב׳ 2017 06:45 PM,‏ "Seungjun Nah" <notifications@github.com>
כתב:

**Comment by SeungjunNah** [comment]
The architecture of discriminator is a little bit different, but either is fine. You would easily figure out the discriminator architecture in model.lua, function generate_discriminator.
Also, the default minibatch size is 4 in this code, which leads to a little bit better PSNR.

**Comment by ghost** [comment]
Ok ill try it. Thank you very much!

בתאריך 3 בנוב׳ 2017 06:54 PM,‏ "Seungjun Nah" <notifications@github.com>
כתב:

**Comment by HaoLiuHust** [comment]
@SivanDoveh have you finished the work?

**Comment by ghost** [comment]
No..

בתאריך 21 בנוב׳ 2017 11:46,‏ "Liu, Hao" <notifications@github.com> כתב:
