### ISSUE TITLE
 can provide a pre-trained CPU model？

### ISSUE THREAD

**Issue by zivenni** [SeungjunNah/DeepDeblur_release#12]
As I do not have a GPU machine, so  can provide a pre-trained CPU model？

thanks.

**Comment by SeungjunNah** [comment]
Currently, our code supports cuda + cudnn environment only and cpu training/test is not supported.
If you need cpu model only, then you can download it from [here](https://drive.google.com/file/d/1Egln7GLlxO0ZM0_2QZiJQ45G9Ua3XgZl/view?usp=sharing).
But do you run the model with our code?
Torch nn package is not really well optimized and GPU implementation is much more efficient in terms of memory usage.
But if you should, I will need to add some lines to the code.

**Comment by cyberbeat** [comment]
I am also interested in testing it with CPU only with your code.

**Comment by SeungjunNah** [comment]
PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
