### ISSUE TITLE
Provide the blurring generation code？

### ISSUE THREAD

**Issue by KengChiLiu** [SeungjunNah/DeepDeblur_release#13]
Hi, @SeungjunNah . Thanks for the work.
I'm working on experiment which need to generate blurring effect.
Do you think it is OK for you to provide the code of blurring generation ?
Thank you~

**Comment by SeungjunNah** [comment]
Hi @KengChiLiu,
I don't have the exact blur generation code from provided GOPRO_Large_all dataset, as I generated the dataset directly from videos.
However, it is quite easy to generate blurry images.
Here is an example with torch.

```lua
require 'image'
img1 = image.load(filename1)
img2 = image.load(filename2)

signal1 = torch.pow(img1, 2.2)
signal2 = torch.pow(img2, 2.2)

signal_blur = (signal1 + signal2)/2
img_blur = torch.pow(signal_blur, 1/2.2)
```
Practically, it would be enough to assume linear CRF. In that case, followings would suffice.
```lua
require 'image'
img1 = image.load(filename1)
img2 = image.load(filename2)
img_blur = (img1 + img2)/2
```

**Comment by ghost** [comment]
hi , so the **sharp** image in the dataset are with linear crf?
signal1 = image.load(filename1)
OR
img1 = image.load(filename1)
signal1 = torch.pow(img1, 2.2)

thanks!

**Comment by SeungjunNah** [comment]
A sharp image is taken with nonlinear CRF.
'img1' is the sharp image, and 'signal1' is the linearized value by applying inverse CRF.

**Comment by ghost** [comment]
thanks!
when you mention your psnr and ssim results: the blurry dataset is with gamma = 2.2 or linear crf?
thanks!

**Comment by hazirbas** [comment]
Hi @SeungjunNah ,
I would like to blur my videos and I have seen your code above. Is this how I should use my every consecutive frames to blur a video?

Thanks,
Caner

**Comment by SeungjunNah** [comment]
@SivanDoveh 
Sorry, I missed your question. For the GOPRO dataset the PSNR is measured from gamma=2.2 blurry images. For the Kohler dataset, linear CRF is assumed.

**Comment by SeungjunNah** [comment]
@hazirbas 
If the motion between your video frames is not big, yes.
In case you want your generated frames to be aligned with original frames, then you should take the average of N+1 frames (N/2 from past, 1 as self, N/2 from future).
However, if the motion in your videos was too fast, then step artifacts may occur on your synthesized images.
