### ISSUE TITLE
When str will be 2 in shortcut(str)?

### ISSUE THREAD

**Issue by ghost** [SeungjunNah/DeepDeblur_release#14]
Hi,
what will be the case when input and output will not be with same third dimension? there is always conv at the beginning of every scale-level so when this case will happen? 
Also, i don't understand what the bold part should do

i'm talking on this function : 

function ResBlock(filtsize, nStates, inStates)	
	local function shortcut(str)
		local str = str or 1
		if str == 1 then
			return nn.Identity()
		else
			**local str = 2
			return nn.Sequential()
				:add(nn.SpatialAveragePooling(1,1, str,str))
				:add(nn.Concat(2))
					:add(nn.Identity())
					:add(nn.MulConstant(0))**
		end
	end

Thanks!!
Sivan

**Comment by SeungjunNah** [comment]
Hi,
str is always 1 for this code.
The ResBlock is originated from [fb.resnet.torch](https://github.com/facebook/fb.resnet.torch).
The 'else' statement is not removed just for experimental purposes.
