### ISSUE TITLE
data processing 

### ISSUE THREAD

**Issue by ghost** [SeungjunNah/DeepDeblur_release#16]
Hi!
in the paper you write that you subtract 0.5 from input and output but in the code you don't do it. which one is correct?

also you relate to the images in the data augmentation part as they have values between [0,1]
in the test set i noticed that there are images with values higher than 1

thanks!

**Comment by SeungjunNah** [comment]
The 0.5 subtraction is performed inside the network by nn.AddConstant layer.
You may refer to model.lua: line 137-138, line 162&205.

I don't get how the test image value could be larger than 1.
Could you tell me when that happens?

**Comment by ghost** [comment]
Hi!
I am not familiar with lua so i relying on the paper and on parts of the
code i can understand.
Thanks for the first answer i will check it again!

second question:
I uploaded some images from the test image file and checked for min and max
value to make sure they're the same but in the test file some images were
with 1.5 max

Thanks
sivan

בתאריך 19 בדצמ׳ 2017 02:23 AM,‏ "Seungjun Nah" <notifications@github.com>
כתב:

The 0.5 subtraction is performed inside the network by nn.AddConstant layer.
You may refer to model.lua: line 137-138, line 162&205.

I don't get how the test image value could be larger than 1.
Could you tell me when that happens?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SeungjunNah/DeepDeblur_release/issues/16#issuecomment-352600486>,
or mute the thread

**Comment by SeungjunNah** [comment]
Still I don't get why the maximum value could be over 1.
Could you give me the name of the file, including the address?
For example, GOPRO_Large\test\GOPR0384_11_00\blur_gamma\000001.png

**Comment by SeungjunNah** [comment]
Sorry, I accidentally clicked the close button.

Still I don't get why the maximum value could be over 1.
I would expect the image loading functions to clip the value range.
Could you please give me the name of the file, including the address?
For example, GOPRO_Large\test\GOPR0384_11_00\blur_gamma\000001.png

**Comment by ghost** [comment]
hi i can't find the exact image right now i will try to find it again later.
about the 0.5 subtraction , there was a special reason why you didn't
subtract  0.5 in the same place you clipped the values after the
augmentation?
if i understand right then the subtract purpose is to make the data centered

Thanks alot!!
sivan

2017-12-19 9:00 GMT+02:00 Seungjun Nah <notifications@github.com>:

**Comment by SeungjunNah** [comment]
Hi @SivanDoveh 
I placed the code in NN architecture simply because processing in gpu is faster.
Subtracting 0.5 at the beginning of the network and adding 0.5 at the end of the network is computationally equivalent to operating on data outside the network.
You can put it in the data preparation function (which is done in cpu here).

**Comment by ghost** [comment]
OK thanks !
