### ISSUE TITLE
opts.lua in function parse

### ISSUE THREAD

**Issue by liupengfei1234** [SeungjunNah/DeepDeblur_release#18]
Hi！Thank you for your awesome code, when I run the demo, I meet the problem, can you help me? 
in mode r  at /tmp/buildd/torch7-0.9.99/pkg/torch/lib/TH/THDiskFile.c:649
stack traceback:
        [C]: at 0x7f85d59e74f0
        [C]: at 0x7f85cc86c220
        [C]: in function 'DiskFile'
        /usr/share/lua/5.1/torch/File.lua:405: in function 'load'
        .../code/opts.lua:63: in function 'parse'
        demo.lua:14: in main chunk

**Comment by SeungjunNah** [comment]
Hi,
Did you download the provided model?
Line 63 in opts.lua is for loading previously saved optional arguments.
Its location should be experiment/release_scale3_adv_gamma/opt

**Comment by liupengfei1234** [comment]
Thanks for the reply, I put the model on the right location, but meet a new error: unknown Torch class <nn.PixelShuffle>model.lua:287: in function 'load_main_model'
 model.lua:328: in main chunk
 [C]: in function 'dofile'
  demo.lua:21: in main chunk
Have you ever meet the problem? And noticed that I have not installed the torchx of the dependencies,
will it cause the error? Could you introduce how to build it briefly?  Thank you~

**Comment by SeungjunNah** [comment]
You will need to install torchx.
Type on shell:
```
luarocks install torchx
```
But I think your problem with nn.PixelShuffle would be different one.
As I have saved the model with cuda and cudnn version, failing to install torch with proper CUDA settings may cause problem while loading the saved model.
You can check by after loading torch interpreter by typing th on shell, and type followings:
```lua
require 'cutorch'
require 'nn'
require 'cunn'
require 'cudnn'

```
Does each of them load corresponding package correctly?

**Comment by liupengfei1234** [comment]
I have installed torchx successfully, the problem isn't solved as you say. The result of checking is as follows, can you tell me which option should take care, and I don't know where makes the error. Thank you very much!
'cutorch': getPeerToPeerAccess : function: 0x401c59e0
  getStream : function: 0x41b3d130
  getDeviceCount : function: 0x401b0590
  setHeapTracking : function: 0x41194308
  manualSeedAll : function: 0x401b2898
  getRNGState : function: 0x41481d40
  setKernelPeerToPeerAccess : function: 0x4118f198
  reserveBlasHandles : function: 0x411a6888
  setDefaultStream : function: 0x41b3d1f0
   ... ...
'nn': VolumetricMaxUnpooling : {...}
  ConcatTable : {...}
  MV : {...}
  SpatialAveragePooling : {...}
  SpatialConvolutionMM : {...}
  Reshape : {...}
... ...
'cunn': it appears 'true'
'cudnn': SpatialCrossEntropyCriterion : {...}
  VolumetricConvolution : {...}
  SpatialAveragePooling : {...}
  C : userdata: 0x4054b470
  benchmark : false
  _Pooling : {...}
  SpatialBatchNormalization : {...}
  fastest : false
... ...

**Comment by SeungjunNah** [comment]
It seems like your installation with gpu is valid.
I'm sorry, but I can't reproduce the same error.
Would you please try loading the model on the interpreter?
Assuming you are in "DeepDeblur_release" directory,
```lua
require 'nn';
require 'cunn';
require 'cudnn';
model = torch.load('experiment/release_scale3_adv_gamma/models/model-450.t7')
```
If this fails, then I guess there could be problem in the torch installation.
Else, there may be some bugs in my code, and would appreciate if you could give more more information whatever you think necessary, such as cuda, cudnn versions.
I have tested this code with cuda 8.0 + cudnn 5.1 and 6.0.
(cudnn 6.0 requires manual build of corresponding branch from [cudnn.torch](https://github.com/soumith/cudnn.torch/tree/R6))

**Comment by liupengfei1234** [comment]
Thanks for your reply! I load the model on the interpreter.
 If the model is 'gamma':
/usr/share/lua/5.1/torch/File.lua:343: unknown Torch class <nn.PixelShuffle>
stack traceback:
        [C]: in function 'error'
 If the model is 'lin':
/usr/share/lua/5.1/torch/File.lua:351: cuda runtime error (2) : out of memory at /tmp/buildd/torch7-0.9.99/extra/cutorch/lib/THC/THCGeneral.c:608
stack traceback:
        [C]: in function 'read'
        /usr/share/lua/5.1/torch/File.lua:351: in function </usr/share/lua/5.1/torch/File.lua:245>
        [C]: in function 'read'
        /usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/nn/Module.lua:158: in function 'read'
        /usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/nn/Module.lua:158: in function 'read'
        /usr/share/lua/5.1/nn/Module.lua:158: in function 'read'
        /usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:409: in function 'load'
        [string "model = torch.load('experiment/release_scale3..."]:1: in main chunk
        [C]: in function 'xpcall'
        /usr/share/lua/5.1/trepl/init.lua:669: in function 'repl'
        /usr/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
        [C]: at 0x00406670
cuda version: 
CUDA Version 8.0.61
cudnn version: 
#define CUDNN_MAJOR      6
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 21
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
I can't find where the error from. Thank you for your consideration and I will be looking forward to your reply.

**Comment by liupengfei1234** [comment]
Thanks for your reply! I load the model on the interpreter.
If the model is 'gamma':
/usr/share/lua/5.1/torch/File.lua:343: unknown Torch class <nn.PixelShuffle>
stack traceback:
[C]: in function 'error'
If the model is 'lin':
/usr/share/lua/5.1/torch/File.lua:351: cuda runtime error (2) : out of memory at /tmp/buildd/torch7-0.9.99/extra/cutorch/lib/THC/THCGeneral.c:608
stack traceback:
[C]: in function 'read'
/usr/share/lua/5.1/torch/File.lua:351: in function </usr/share/lua/5.1/torch/File.lua:245>
[C]: in function 'read'
/usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
/usr/share/lua/5.1/nn/Module.lua:158: in function 'read'
/usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
/usr/share/lua/5.1/nn/Module.lua:158: in function 'read'
/usr/share/lua/5.1/nn/Module.lua:158: in function 'read'
/usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
/usr/share/lua/5.1/torch/File.lua:409: in function 'load'
[string "model = torch.load('experiment/release_scale3..."]:1: in main chunk
[C]: in function 'xpcall'
/usr/share/lua/5.1/trepl/init.lua:669: in function 'repl'
/usr/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
[C]: at 0x00406670
cuda version:
CUDA Version 8.0.61
cudnn version:
#define CUDNN_MAJOR 6
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 21

#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
I can't find where the error from. Thank you for your consideration and I will be looking forward to your reply.

**Comment by SeungjunNah** [comment]
Oh, your error log says you need more GPU memory.
This part:
/usr/share/lua/5.1/torch/File.lua:351: cuda runtime error (2) : out of memory at /tmp/buildd/torch7-0.9.99/extra/cutorch/lib/THC/THCGeneral.c:608

I ran the code with 12GB memory GPUs such as GTX Titan X (Maxwell).

**Comment by liupengfei1234** [comment]
It works well when the GPU memory remain enough,  but only the model 'linear' works normally. When I 
try to test the gamma model, it shows error as before: 
qlua: /usr/share/lua/5.1/torch/File.lua:343: unknown Torch class <nn.PixelShuffle>
stack traceback:
        [C]: at 0x7efe179ad4f0
        [C]: in function 'error'
        /usr/share/lua/5.1/torch/File.lua:343: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/nn/Module.lua:158: in function 'read'
        /usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/nn/Module.lua:158: in function 'read'
        /usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        ...
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/nn/Module.lua:158: in function 'read'
        /usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /usr/share/lua/5.1/torch/File.lua:409: in function 'load'
        model.lua:287: in function 'load_main_model'
        model.lua:328: in main chunk
        [C]: in function 'dofile'
        demo.lua:21: in main chunk
Lua 5.1  Copyright (C) 1994-2008 Lua.org, PUC-Rio
It had occurred once, have you got some method about the error, thank you ~

**Comment by SeungjunNah** [comment]
PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
