### ISSUE TITLE
Is there any other source of datasets?

### ISSUE THREAD

**Issue by pz0910** [SeungjunNah/DeepDeblur_release#19]
Failed to download the dataset for some reason.
Can you provide another link to download the datasets

**Comment by SeungjunNah** [comment]
You can try downloading from this unofficial link: [GOPRO_Large](https://www.dropbox.com/s/49agq840mcr02vp/GOPRO_Large.zip?dl=0)

**Comment by fengxin619** [comment]
@SeungjunNah   sorry...but could you provide a baidu cloud disk link ?  I can't visit google...

**Comment by SeungjunNah** [comment]
@nextfeixiag 
Hi, this is another alternative [download link](https://cv.snu.ac.kr/~snah/Deblur/dataset/GOPRO_Large.zip)

**Comment by abhishekvahadane** [comment]
The Download link is not working. @SeungjunNah

**Comment by SeungjunNah** [comment]
@abhishekvahadane 
Which link do you mean?
The all the links (google drive) in README seems to be working.
The other links here are unofficial alternatives that are not guaranteed to be stable.

**Comment by abhishekvahadane** [comment]
Yes, the Google drive links are working fine but it's huge 9.5G. I meant the above link and alternative link mentioned in this issue.

**Comment by abhishekvahadane** [comment]
Okay. They are working. Sorry for the trouble.

**Comment by SeungjunNah** [comment]
@abhishekvahadane 
So here is the summary:
README link: Google drive, working
Alternative link 1: Dropbox, traffic limited per day. May or may not work
Alternative link 2: our server link. It was fixed just a moment ago.

**Comment by abhishekvahadane** [comment]
Thanks for the summary. @SeungjunNah Any exception on use of trained network on some category of images?

**Comment by SeungjunNah** [comment]
They are class agnostic, so in principle, there are no restrictions except some physical conditions such as:
* extremely large blurs
* the blurs that rarely happens from my hands (the models could have overfit to my handshake blur)
* Defocus blur (GoPro camera has focal length set to infinity)
* severely noisy images (training data augmented with AWGN with some strength)
* Camera response function that is very different from GoPro or gamma function.
