### ISSUE TITLE
Provide Docker image?

### ISSUE THREAD

**Issue by ysh329** [SeungjunNah/DeepDeblur_release#2]
Thanks in advance.

**Comment by SeungjunNah** [comment]
I'm sorry but I haven't used docker before, and not familiar with it.
It is not difficult to install cuda, cudnn, and torch though.
You can download cuda from https://developer.nvidia.com/cuda-downloads,
cudnn from https://developer.nvidia.com/cudnn,
and easily install torch following instructions from http://torch.ch/docs/getting-started.html#_
Currently, the master branch of torch supports cudnn 5.1 and optionally use cudnn 6.0 by compiling https://github.com/soumith/cudnn.torch/tree/R6.

**Comment by SeungjunNah** [comment]
I'm sorry but I haven't used docker before, and not familiar with it.
It is not difficult to install cuda, cudnn, and torch though.
You can download cuda from https://developer.nvidia.com/cuda-downloads,
cudnn from https://developer.nvidia.com/cudnn,
and easily install torch following instructions from http://torch.ch/docs/getting-started.html#_
Currently, the master branch of torch supports cudnn 5.1. 
You can optionally use cudnn 6.0 by typing "luarocks make" in R6 branch: https://github.com/soumith/cudnn.torch/tree/R6

**Comment by ysh329** [comment]
@SeungjunNah Thanks your reply!
