### ISSUE TITLE
Problem with the dataset

### ISSUE THREAD

**Issue by NinetailsBear9** [SeungjunNah/DeepDeblur_release#22]
The sharp frames provided are not continuous?
Because after I averaged the 7 frames and got i terrible blur images and them are much different with the blur images provided~

**Comment by SeungjunNah** [comment]
Hi @NinetailsBear9,
Could you provide more details?
What images did you use to take the average?
Also, in which way, specifically?

**Comment by NinetailsBear9** [comment]
I just tried the sharp images in your dataset (GOPR0372_07_00)
i did average directly on 000047.png~000053.png(7 images) and also tried the gamma = 2.2 (translate from image to signal , average, and translate back), the both results are terrible

**Comment by SeungjunNah** [comment]
Hi @NinetailsBear9,
You should merge frames from GOPRO_Large_all, not from GOPRO_Large.
The frames located at GOPRO_Large/train/GOPR0372_07_00/sharp are the corresponding GT images for the blur frames that are already been averaged. The blur frames are time disjoint, and the sharp frames are the middle sharp frame among the averaged frames. Thus, they are frames with intervals.

Try averaging frames at GOPRO_Large_all/train/GOPR0372_07_00/000323.png ~ 000329.png

**Comment by NinetailsBear9** [comment]
You're right, Thanks for your help~
