### ISSUE TITLE
experiment algorithms

### ISSUE THREAD

**Issue by kk5pengke** [SeungjunNah/DeepDeblur_release#23]
Thanks for your work. I ’m comparing different deblurring algorithms. and I didn't find the Sun' implementation in github about his paper “Learning a convolutional neural network for non-uniform motion blur removal”，which is used in your experiment. did you realize
it yourself ?

**Comment by SeungjunNah** [comment]
The authors' own implementation is available on Jian Sun's [website](http://gr.xjtu.edu.cn/web/jiansun/codes).
Link to the specific code is [here](http://gr.xjtu.edu.cn/c/document_library/get_file?folderId=2076150&name=DLFE-78101.zip).
