### ISSUE TITLE
Got errors 

### ISSUE THREAD

**Issue by Harry-675** [SeungjunNah/DeepDeblur_release#26]
stack traceback:
	...h/install/share/lua/5.1/cudnn/SpatialFullConvolution.lua:31: in function 'resetWeightDescriptors'
	...h/install/share/lua/5.1/cudnn/SpatialFullConvolution.lua:105: in function <...h/install/share/lua/5.1/cudnn/SpatialFullConvolution.lua:103>
	[C]: in function 'xpcall'
	/home/harry/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/harry/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function </home/harry/torch/install/share/lua/5.1/nn/ConcatTable.lua:9>
	[C]: in function 'xpcall'
	/home/harry/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/harry/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/harry/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/harry/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/harry/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/harry/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/harry/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...e/harry/torch/install/share/lua/5.1/nn/ParallelTable.lua:12: in function <...e/harry/torch/install/share/lua/5.1/nn/ParallelTable.lua:10>
	[C]: in function 'xpcall'
	/home/harry/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/harry/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	test.lua:49: in function 'get_output'
	test.lua:128: in function 'get_output_img'
	test.lua:268: in function 'demo'
	demo.lua:38: in main chunk

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: at 0x7f337fb50f50
	[C]: in function 'error'
	/home/harry/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/harry/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	test.lua:49: in function 'get_output'
	test.lua:128: in function 'get_output_img'
	test.lua:268: in function 'demo'
	demo.lua:38: in main chunk
Lua 5.1  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> 
Please helo me with this!

**Comment by SeungjunNah** [comment]
Hi @Harry-675,
Have you matched cudnn version of torch and your installed version?
torch installs cudnn 5.1 by default.
To use a more recent cudnn version with torch, you may try 
```bash
cd ~/torch/extra/cudnn
git checkout R6 # replace with a specefic version you would like
luarocks make
```

**Comment by JQJ001** [comment]
Hi, @SeungjunNah, thanks for your sharing.
I had also met the same problem as Harry-675 and my cudnn's version is 7.5.1。
 Can you tell me how to solve it? Thank you!

**Comment by JQJ001** [comment]
when I typed 'qlua -i demo.lua -load -save release_scale3_adv_lin -blur_type linear -type cudaHalf', above error occured. :(
When I typed 'qlua -i demo.lua -load -save release_scale3_adv_gamma -blur_type gamma2.2 -type cudaHalf' , the code can run successfully. :)

**Comment by SeungjunNah** [comment]
@GitHub0830 
Oh, it's weird that they have different behaviors.
I will look into this later.
I'm out of office for a few days.

**Comment by JQJ001** [comment]
Ok, thanks.

**Comment by SeungjunNah** [comment]
PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
