### ISSUE TITLE
 qlua：cannot find the command

### ISSUE THREAD

**Issue by liupengfei1234** [SeungjunNah/DeepDeblur_release#28]
Dear author：When I run the demo, error: cannot find 'qlua' command，the command 'lua'  is from package  'lua5.1' (universe). I set up the lua on 5.1 version, but it can not identify the 'qlua' command, do you know which causes the problem? Waiting for your reply. Thank you！

**Comment by SeungjunNah** [comment]
Could you check if you can run the command ```th```?
You can run ```qlua``` after installing torch.

**Comment by liupengfei1234** [comment]
I can run the command th, then coming into the torch interface.

**Comment by SeungjunNah** [comment]
I see.
Then probably your torch installation skipped it.
Could you check if your installed luarocks list includes qtlua or qttorch by typing ```luarocks list```?
If not, you may install them with following commands.
```bash
luarocks install qtlua
luarocks install qttorch
```

**Comment by liupengfei1234** [comment]
When I input 'luarocks install qtlua', it says:
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
CMake Error at /usr/share/cmake-3.5/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:38 (FIND_PACKAGE)
-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_qtlua-scm-1-9587/qtlua/build/CMakeFiles/CMakeOutput.log".
Does I need to download qt?

**Comment by SeungjunNah** [comment]
No, that is nor required.
Did you run ```bash install-deps``` before intalling torch?
It should have installed all the requirements to install qlua.

I recommend you to re-install torch.

If this problem further complicates you, then you can run without qt support.
You can run demo with ```th``` if you comment some lines used to display images from test.lua:
[line 264](https://github.com/SeungjunNah/DeepDeblur_release/blob/master/code/test.lua#L264) and [line 270](https://github.com/SeungjunNah/DeepDeblur_release/blob/master/code/test.lua#L270).

Those are lines where I used image.display function.
You will find the results saved in dataset/examples/deblurred_xxx.

**Comment by liupengfei1234** [comment]
I re-install torch, problem of 'qlua' solved, but it comes:  
home/bacon/torch/install/share/lua/5.1/xlua/init.lua:360: module 'liblua_png' not found:
        no field package.preload['liblua_png']
        no file '/home/bacon/.luarocks/share/lua/5.1/liblua_png.lua'
        no file '/home/bacon/.luarocks/share/lua/5.1/liblua_png/init.lua'
        no file '/home/bacon/torch/install/share/lua/5.1/liblua_png.lua'
        no file '/home/bacon/torch/install/share/lua/5.1/liblua_png/init.lua'
        no file './liblua_png.lua'
        no file '/home/bacon/torch/install/share/luajit-2.1.0-beta1/liblua_png.lua'
        no file '/usr/local/share/lua/5.1/liblua_png.lua'
I find a solution to use aptitude replacing apt-get, But it appears the same problem too.
When install torch, as follows:
libgraphicsmagick1-dev : dependency: libwmf-dev ,not installed
                          dependency: libfreetype6-dev not installed
                          dependency: libtiff-dev
                          dependency: zlib1g-dev not installed or
                                  libz-dev
                          dependency: libpng-dev

**Comment by SeungjunNah** [comment]
It seems like you didn't run ```bash install-deps``` command from [torch install instruction](http://torch.ch/docs/getting-started.html#_).
The required dependencies should be installed when you run it.
Note that you would need sudo permission.

**Comment by liupengfei1234** [comment]
problem solved, thank you very much~
I will always support you！
