### ISSUE TITLE
Can this algorithm be implemented on a Windows system?

### ISSUE THREAD

**Issue by robbiewongBD** [SeungjunNah/DeepDeblur_release#31]
Can this algorithm be implemented on Windows system?

**Comment by SeungjunNah** [comment]
Torch is officially not supported on Windows.
Recently I'm moving on to PyTorch.
If I reimplement on PyTorch, I'll release it.

**Comment by hanshan1** [comment]
looking forward to your pytorch version ,i want to quote your paper

**Comment by SeungjunNah** [comment]
PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
