### ISSUE TITLE
segmentation Fault with Cudnn

### ISSUE THREAD

**Issue by surajitsaikia27** [SeungjunNah/DeepDeblur_release#32]
While i am trying to run the demo I am getting this error.

Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.5Segmentation fault (core dumped)

**Comment by SeungjunNah** [comment]
I'm not sure about the cause.
Which cudnn version did you use?
Torch7 uses cudnn 5.1 by default.
You can switch to newer versions by the following command:
```bash
cd torch/extra/cudnn
git checkout R7   # R6 if your cudnn version is 6
luarocks make
```

**Comment by SeungjunNah** [comment]
PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
