### ISSUE TITLE
Demo code doesn't work for images of resolution 1920 × 1080

### ISSUE THREAD

**Issue by sbanerj2** [SeungjunNah/DeepDeblur_release#34]
The demo code doesn't run if I use images of resolution, 1920 × 1080. However, it works for the images provided which have a dimension of 1280 × 720. 
Torch version used: 7.0
cudnn 5.1 
GPU: NVIDIA GeForce GTX 1080 Ti GPU

**Comment by hanshan1** [comment]
> The demo code doesn't run if I use images of resolution, 1920 × 1080. However, it works for the images provided which have a dimension of 1280 × 720.
> Torch version used: 7.0
> cudnn 5.1
> GPU: NVIDIA GeForce GTX 1080 Ti GPU

And how dia you test the model on your picture?  Looking forward for your replying

**Comment by SeungjunNah** [comment]
@sbanerj2 , @hanshan1 
I'm sorry for the delayed response.
I will enable half precision mode so that it could operate with reduced memory.
I have been out of time these days running a conference. 
It lasts until this week, so please let me take some time to work on it.

**Comment by SeungjunNah** [comment]
PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
