### ISSUE TITLE
Help in getting (building) torchx package

### ISSUE THREAD

**Issue by sarahghali** [SeungjunNah/DeepDeblur_release#37]
Dear Seungjun,

You have listed the Dependencies:
torch7
torchx
cudnn
Every thing is done, except torchx, I have no idea how to build it. It is a package which is implemented using lua, there is a cmakelists file, but I am not able to build it and generate the package torchx. Could you please guide me in this regards?
Thanks in advance

**Comment by SeungjunNah** [comment]
You can simply type in the shell: 
```bash
luarocks install torchx
```

**Comment by suke27** [comment]
it report : Error: Failed cloning git repository. using 'luarocks install torchx'

**Comment by SeungjunNah** [comment]
PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
