### ISSUE TITLE
Can this run on windows?

### ISSUE THREAD

**Issue by Zhiwei-Wei** [SeungjunNah/DeepDeblur_release#38]
Ubuntu troubles me a lot ...

**Comment by SeungjunNah** [comment]
Installing torch on Windows could be tricky and I never tried to.
If you want the deblurred results on your images, you can send images to my email.

**Comment by SeungjunNah** [comment]
PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
