### ISSUE TITLE
Camera calibration? 

### ISSUE THREAD

**Issue by wonwoolee** [SeungjunNah/DeepDeblur_release#43]
Hi, 
Do you have intrinsic parameters of cameras used to record REDS datasets? 
If you have, can you post it to the web for downloads ?

**Comment by SeungjunNah** [comment]
Hi @wonwoolee,

Unfortunately, I don't have the GoPro6 camera with me. I have been out of Korea for a while and will return in the next month. I will check if my colleagues can help with this.

**Comment by wonwoolee** [comment]
Thanks for quick response. I'll look forward to it. 
:-)

**Comment by SeungjunNah** [comment]
Hi @wonwoolee,

I'm back in Korea and here's the camera parameter together with the calibration images.
[google drive link](https://drive.google.com/file/d/1bcPj-rfFEzS8FBwQIg_uUmAt2IF1bm_N/view?usp=sharing)
The parameters are calculated by matlab.

Please note that the original video frames are recorded in FHD (1920x1080) and were downsampled to HD (1280x720) when generating the dataset. The calculated parameters are for the downsampled resolution. Please refer to the code in the above link for details.

Thank you for waiting.

**Comment by wonwoolee** [comment]
Hi, @SeungjunNah 
Thank you for your help. 
It seems the google drive link is currently shut down due to too many accesses on the file, but I guess the link will open again a few days later. 

Looks like REDS dataset is getting popular ? :-)
Thanks, again
