### ISSUE TITLE
Permission to reuse figures from the paper

### ISSUE THREAD

**Issue by Donkie** [SeungjunNah/DeepDeblur_release#44]
Hi! I'm studying at Chalmers University of Technology and I'm writing a report about motion deblurring in images. I've been using your report as a template for how to carry out my work. So firstly I would like to thank you for the work you have done. Since I'm using a very similar architecture as yours, I would need to show a diagram of the architecture in my report. Is it okay if I reproduce the images of the architecture that you represent in your paper?

Thanks, Daniel

**Comment by SeungjunNah** [comment]
Hi Daniel,

You can find the model figure in the ppt slides I shared in README.md. You can use it under proper ethical standards. Just think of normal plagiarism criterion and if you are good, you can use it for your purpose.

**Comment by Donkie** [comment]
Alright, thank you very much.
