### ISSUE TITLE
can not download pretrained model

### ISSUE THREAD

**Issue by suke27** [SeungjunNah/DeepDeblur_release#45]
hello, i try to run your pretrained model. but seems can not download. is there other link for pretrained model.

**Comment by SeungjunNah** [comment]
Hi @suke27, sorry for the late reply.
Google drive sometimes blocks downloads by the amount of traffic usage.
It seems to be ok now.
Could you try again?
If it is still problematic for you, I will create another link.

**Comment by suke27** [comment]
thank you, i have success to download it. another question, is there other framework version we can try. i means tf or pytorch.

**Comment by SeungjunNah** [comment]
@suke27 
I have no determined plans yet.
I may reimplement this with PyTorch.
If I do, I will update this repository.

**Comment by SeungjunNah** [comment]
PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
