### ISSUE TITLE
Hi！Can this method be used for defocused images?

### ISSUE THREAD

**Issue by nwpuqyj** [SeungjunNah/DeepDeblur_release#46]
Thank you for your code!
I have some problems:
1.I notice that this method is kernel-free method.In theory, if there is a dataset of defocused images, can this method be used for defocused images?
2.A lot of work is tested on the GOPRO dataset. Does the GOPRO dataset have defocused images and corresponding sharp images?

**Comment by SeungjunNah** [comment]
Dear @nwpuqyj,

This method is mainly designed for motion blurs. There's no explicit limitation in theory, but the trained dataset contains motion blur only and no defocus blur.

When I tested the method to defocused images, it worked somehow on lightly defocused images, but not satisfactorily on heavily defocused images.
