### ISSUE TITLE
Implementation details of upconv

### ISSUE THREAD

**Issue by Lucksong** [SeungjunNah/DeepDeblur_release#48]
Hi, Thanks to your great work.
I am not familiar with lua, I want to know the implementation details of upconv.
What is the input of upconv? Restored low resolution image or its high-level features from the resblock?
Is the process of upconv as described below:
(batch ,3, h, w) ——>conv——>(batch, 3*2*2, h, w)——>PixelShuffle(2)——>(batch, 3, 2*h, 2*w)?

**Comment by SeungjunNah** [comment]
Hi @Lucksong,
Yes, you are right. (fixed typo? below)

ratio = 2
(batch, 3, h, w) ——>conv——>(batch, 3*ratio^2, h, w)——>PixelShuffle(2)——>(batch, 3, 2h, 2w)?

You may want to refer to [L106](https://github.com/SeungjunNah/DeepDeblur_release/blob/master/code/model.lua#L106).

**Comment by Lucksong** [comment]
@SeungjunNah Thanks for your help.
