### ISSUE TITLE
Duty cycle of REDS

### ISSUE THREAD

**Issue by tkkcc** [SeungjunNah/DeepDeblur_release#49]
Hi, when creating REDS, you said
> we average the 1920 fps video frames to produce virtual 24 fps blurry video with duty cycle τ= 0.8

Does it mean for every 80(1920/24=80) frames in the 1920 fps video, 64(80*0.8) frames are used to create one blurry frame, and 16 frames are skiped? If so, what is the corresponding clean frame?

Thanks!

**Comment by SeungjunNah** [comment]
Hi @tkkcc,

Let me explain with the original captured video in 120 fps.
In the image below, vertical bars are the frames.
The center frame among the 'Averaged' is the GT sharp frame.

![image](https://user-images.githubusercontent.com/8789158/77553214-dce20980-6ef7-11ea-9bd2-e9b9a6ed3bad.png)

Between the vertical bars, there are 15 interpolated frames (not shown) that are averaged together when synthesizing blur. Thus, total 65 (<del>64</del>) frames are averaged to make a blurry frame.

**Comment by tkkcc** [comment]
Hi, @SeungjunNah. Thank you for reply.

So this `total 64 frames` contains 4 original frames and 60 interpolated frames. And the 3th original frame is GT. Is it right? 

If so, it seems the GT is not exactly the central frame of `total 64 frames`. Is it better to include the 5th original frame? Thus average over 65 frames to make a blurry frame.

**Comment by SeungjunNah** [comment]
Oh, I made a mistake counting the number of frames.
16*4 + 1 = 65 frames are averaged to make a blurry frame.
GT is the center frame.

**Comment by tkkcc** [comment]
Thank! It's clear.
Great work for GOPRO and REDS dataset!
