### ISSUE TITLE
How to test the GoPro dataset using your pre-trained model?

### ISSUE THREAD

**Issue by yff0815** [SeungjunNah/DeepDeblur_release#50]
Hello ，good work, but I have a question.
I would like to test the GoPro dataset using your pre-trained model, and what is the file structure of the test data? 
Looking forward to your reply！

**Comment by SeungjunNah** [comment]
Sorry for the late reply. You can put the dataset as described in [Code](https://github.com/SeungjunNah/DeepDeblur_release#code) part of README.
Also, PyTorch version now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
