### ISSUE TITLE
Can you share the test results for the REDs dataset ?

### ISSUE THREAD

**Issue by phoebe1996511** [SeungjunNah/DeepDeblur_release#52]
excuse me,can you share the test results for the REDs dataset ?

**Comment by SeungjunNah** [comment]
Sure, I plan to do it.
I will release the results with the other results from the NTIRE challenges.

**Comment by phoebe1996511** [comment]
thanks，I'm looking forward to it



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Seungjun Nah"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月26日(星期天) 下午3:08
收件人:&nbsp;"SeungjunNah/DeepDeblur_release"<DeepDeblur_release@noreply.github.com&gt;;
抄送:&nbsp;"张艳芳"<735261373@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SeungjunNah/DeepDeblur_release] Can you share the test results for the REDs dataset ? (#52)





 
Sure, I plan to do it.
 I will release the results with the other results from the NTIRE challenges.

**Comment by SeungjunNah** [comment]
The results on the REDS dataset is now available here: https://github.com/SeungjunNah/DeepDeblur-PyTorch
