### ISSUE TITLE
How can I download the Sharp_Test images for REDS datasets

### ISSUE THREAD

**Issue by pp00704831** [SeungjunNah/DeepDeblur_release#54]
Hello, 
I try to download the REDS datasets from your websites, but it seems like I can not download the 'Sharp' images for testing data, the download link 'test_sharp' can not work, but other links can work.
I am not sure if I use wrong way to download the sharp test data for images deblurring, but the python  code 'download_REDS.py' also does not have the '--test_sharp'  command, so would you share this link for the future? 
Thanks a lot!

**Comment by SeungjunNah** [comment]
Hi @pp00704831,

As we have been hosting REDS related challenges in NTIRE and AIM workshops, I don't have plans to release the test GT. I'm working on public online submission site, but it is taking quite a time. If I release the site, I will notice it.
