### ISSUE TITLE
How can I download uncompressed REDS videos

### ISSUE THREAD

**Issue by TigerZing** [SeungjunNah/DeepDeblur_release#56]
Hello,
Thank you so much for your REDS dataset. 
Currently, I am researching about deblurring for compressed videos, Could I get the uncompressed videos of the REDS dataset? Or Can I use the images of the sharp dataset as uncompressed images?
Hope to receive a good response from you.
Thank you a lot!

**Comment by SeungjunNah** [comment]
Hi @TigerZing,
REDS dataset is constructed to suppress the compression etc. artifacts as much as possible.
The MPEG compressed subset also exists. (blur + compression)
You can download them [here](https://seungjunnah.github.io/Datasets/reds) and find more details in this [slide](https://drive.google.com/file/d/13F6UEyBDFGTiFDyxqLzrPiq4Y2-8BKQE/view?usp=sharing).

**Comment by TigerZing** [comment]
Many thanks for your prompt reply and your slide.
it is obvious to me.
