### ISSUE TITLE
How to generate blur and blur_gamma dataests，sharp datasets mean orginal datasets?

### ISSUE THREAD

**Issue by Williamlizl** [SeungjunNah/DeepDeblur_release#57]

**Comment by SeungjunNah** [comment]
Regarding blur synthesis, you can refer to #13.
GOPRO_Large_all means all the frames used to generate blur.
You can take a look at the description [here](https://seungjunnah.github.io/Datasets/gopro).

**Comment by Williamlizl** [comment]
> Regarding blur synthesis, you can refer to #13.
> GOPRO_Large_all means all the frames used to generate blur.
> You can take a look at the description [here](https://seungjunnah.github.io/Datasets/gopro).

> Regarding blur synthesis, you can refer to #13.
> GOPRO_Large_all means all the frames used to generate blur.
> You can take a look at the description [here](https://seungjunnah.github.io/Datasets/gopro).
`img1 = image.load(filename1)
img2 = image.load(filename2)

signal1 = torch.pow(img1, 2.2)
signal2 = torch.pow(img2, 2.2)

signal_blur = (signal1 + signal2)/2
img_blur = torch.pow(signal_blur, 1/2.2)` 
image.load? or can i use other ways to generate blur images?[https://github.com/codebox/image_augmentor](url)
[https://github.com/aleju/imgaug](url)

**Comment by SeungjunNah** [comment]
What is mentioned in #13 is a torch (Lua) version pseudocode as this repository builds on it.
You can use whichever tool you prefer.

But I'd recommend you to refer to our updated dataset, [REDS](https://seungjunnah.github.io/Datasets/reds) for advanced blur synthesis.
- [paper](http://openaccess.thecvf.com/content_CVPRW_2019/papers/NTIRE/Nah_NTIRE_2019_Challenge_on_Video_Deblurring_and_Super-Resolution_Dataset_and_CVPRW_2019_paper.pdf)
- [slides](https://drive.google.com/file/d/13F6UEyBDFGTiFDyxqLzrPiq4Y2-8BKQE/view?usp=sharing)

**Comment by Williamlizl** [comment]
> What is mentioned in #13 is a torch (Lua) version pseudocode as this repository builds on it.
> You can use whichever tool you prefer.
> 
> But I'd recommend you to refer to our updated dataset, [REDS](https://seungjunnah.github.io/Datasets/reds) for advanced blur synthesis.
> 
> * [paper](http://openaccess.thecvf.com/content_CVPRW_2019/papers/NTIRE/Nah_NTIRE_2019_Challenge_on_Video_Deblurring_and_Super-Resolution_Dataset_and_CVPRW_2019_paper.pdf)
> * [slides](https://drive.google.com/file/d/13F6UEyBDFGTiFDyxqLzrPiq4Y2-8BKQE/view?usp=sharing)

every sharp photo matches the blurred photo? or just sharp the original photo

**Comment by SeungjunNah** [comment]
I'm not sure if I understand your question.
In GOPRO_Large, I provide the blurry and the sharp image pairs that are temporally center-aligned.
In GOPRO_Large_all, I provide all the sharp frames I used to generate blurry images.

**Comment by Williamlizl** [comment]
I mean if I have one original image, then I generate the paired blurry image.
But for the sharp image, I also need to generate it by the original image?

**Comment by SeungjunNah** [comment]
A sharp image is the original image itself.

You need multiple sharp images to synthesize a blurry image.

**Comment by Williamlizl** [comment]
> A sharp image is the original image itself.
> 
> You need multiple sharp images to synthesize a blurry image.
Thank you, I will try it.

**Comment by Williamlizl** [comment]
> A sharp image is the original image itself.
> 
> You need multiple sharp images to synthesize a blurry image.

Thank you, I will try it.
