### ISSUE TITLE
blur images generation issue

### ISSUE THREAD

**Issue by pohanhuang** [SeungjunNah/DeepDeblur_release#59]
Hi,
First, thanks for your hard work on image/video deblurring!
You mentioned that GOPRO camera and then averaged varying numbers (7 - 13) of successive latent frames to produce blurs of different strengths in the paper.
I am wondering is there a relation in GOPRO_Large between blur image and the sharp images (varying numbers (7 - 13)) that generate them.
(eg. GoPro_Large/train/GOPR0372_07_00/blur/000047.png is built from GOPRO_Large_all/train/GOPR0372_07_00/000044.png ~ 000050.png)

I have already read all related issues about blur image generation, and there is no clue to my problem.

Thanks for your work !!

Looking forward to hearing from you soon.

**Comment by SeungjunNah** [comment]
Hi @hhcs9527,

The blurry frame `GOPRO_Large/train/GOPR0372_07_00/blur_gamma/000047.png` is generated by merging
`GOPRO_Large_all/train/GOPR0372_07_00/000323.png` ~ `000329.png`. (1st ~ 7th frame)
The frame number in the file name itself is not important but the relative order in the sequence is important.
In a sequence `GOPRxxxx_yy_zz`, yy number of frames are used to make a blur.

**Comment by pohanhuang** [comment]
Hi @SeungjunNah,
Thanks for your quick reply, and I appreciate the answer!!!

Thanks for your work again!

**Comment by AloneGu** [comment]
> Hi @hhcs9527,
> 
> The blurry frame `GOPRO_Large/train/GOPR0372_07_00/blur_gamma/000047.png` is generated by merging
> `GOPRO_Large_all/train/GOPR0372_07_00/000323.png` ~ `000329.png`. (1st ~ 7th frame)
> The frame number in the file name itself is not important but the relative order in the sequence is important.
> In a sequence `GOPRxxxx_yy_zz`, yy number of frames are used to make a blur.

so what does `zz` means?

**Comment by SeungjunNah** [comment]
Hi @AloneGu,

You can ignore `zz`.
When I generated multiple sequences from a long video, `zz` is used to differentiate them.
As all the frames are provided for each sequence, you don't have to consider them.

**Comment by wyx2001-0615** [comment]
Hi, I am currently trying to use GoPro to generate pairs of blurred images, creating blurred images from videos I recorded myself. Could you please share the code for generating blur with GoPro? Thank you.

**Comment by SeungjunNah** [comment]
@wyx2001-0615 You can simply take average of N frames in sRGB space to make a blurry image and take the middle frame among the averaged as the corresponding sharp frame. The old blur generation code for GoPro was written in Lua long time back and I don't have it now.
