### ISSUE TITLE
dataset gopro_large

### ISSUE THREAD

**Issue by ldlshizhu** [SeungjunNah/DeepDeblur_release#60]
Thank you for your contribution！ Can you tell me what the pictures in blur_gamma folder in gopro_large dataset are used for?I thought only blur and sharp were needed to train in the experiment。thanks again！

**Comment by SeungjunNah** [comment]
Hi @ldlshizhu,

It is the opposite.
`blur_gamma` is the input data considering the gamma function as the inverse camera response curve as described in the paper.
`blur` assumes a linear camera response which may not generalize well.

**Comment by noranali** [comment]
> blur_gamma

hi @SeungjunNah, thank you for your paper and code
this is meaning that you used the blur gamma in your paper ?

**Comment by SeungjunNah** [comment]
@noranali
Yes, that is correct.

**Comment by noranali** [comment]
> @noranali Yes, that is correct.

@SeungjunNah 
thank you for your replay . but please can you help me and get me the link to download kohler dataset

**Comment by SeungjunNah** [comment]
@noranali 
Have you tried downloading from this page?
https://webdav.tuebingen.mpg.de/pixel/benchmark4camerashake/
