### ISSUE TITLE
여기서 제공하는 dataset은 무료로 이용해도 되는 건가요??

### ISSUE THREAD

**Issue by wjs2063** [SeungjunNah/DeepDeblur_release#63]
무료로 이용해도되는지 궁금합니다 ㅠㅠ

**Comment by SeungjunNah** [comment]
Please refer to the license notification on [the dataset page](https://seungjunnah.github.io/Datasets/gopro).

**Comment by SeungjunNah** [comment]
CC BY 4.0 license: https://creativecommons.org/licenses/by/4.0/
