### ISSUE TITLE
diff image is zero-valued

### ISSUE THREAD

**Issue by haow85** [SeungjunNah/DeepDeblur_release#64]
Dear code contributors:

I tested the algorithm package using the following command :

`python demo.py --gpu 0 --train_dir pretrained --exp_name multi_skip --image "photo.jpg"`

, and in the function compute_psnr() of utils.py, I got a math domain error due to Inf value for log10. The reason is because img1 - img2 is zero valued array, which means img1 and img2 are the same.

How do I fix the issue ?

Best Regards,
Hao Wang

**Comment by haow85** [comment]
I found in the test function of demo.py the input image directory is required to contain an input_b1 image and a target_s1 image. I think they are referring to blurry image and sharp image, but in my test case I do not have a target sharp image for performance evaluation.

I commented out the line compute_psnr and the print function below. The error disappeared, but when I took a look at the resulting deblurred image, I got a blank white canvas with a broken yellow line.

I think the algorithm failed in the case.

**Comment by SeungjunNah** [comment]
Hi @haow85,

This is a torch version repository that uses the Lua language and you are using a python command.
Also, based on the input argument you used, the code you used doesn't seem to be related to the [Pytorch version](https://github.com/SeungjunNah/DeepDeblur-PyTorch) of this code repository.

Could you check if you are referring to this repository?
