### ISSUE TITLE
Why the discriminator's architecture in the code is not identical to the paper's version?

### ISSUE THREAD

**Issue by orashi** [SeungjunNah/DeepDeblur_release#7]
Hey @SeungjunNah, thanks again for releasing this code. I noticed that in the code, first two layers of the discriminator are conv 3-32 5\*5 stride1, 32-32 5\*5 stride2,which is not identical to the paper's version that places only conv 3-32 5\*5 stride2.
Is this a miss or there is a reason for it? And which version has a better performance in terms of PSNR or SSIM in practice?

**Comment by SeungjunNah** [comment]
Hi @orashi,
Sorry for delayed response.
We have tried several experiments after the submission and tried to use discriminator with a larger receptive field. I forgot about the differentiation of the published paper and this source code.
Thanks for mentioning.
However, it is hard to say new one(this repository code) has better performance, as stronger discriminator does not lead generator to achieve higher numerical performance.
