### ISSUE TITLE
How can I get the same results in your paper ?

### ISSUE THREAD

**Issue by Git-H2K** [SeungjunNah/DeepDeblur_release#8]
Hi! I compiled your code and got deblurred results.
Next, I calculated PSNR between each deblurred result and sharp image, and averaged them.

However, I got different results.

GOPROSET
PSNR (paper, K=1) 28.93 dB
PSNR (test, K=1, blurtype & model = blur) 28.49 dB
PSNR (test, K=1, blurtype & model = blur_gamma) 29.12 dB

OS : ubuntu 16.04
VGA : titan X

How can I get the same results in your paper ?

Thanks!
HH.

**Comment by SeungjunNah** [comment]
Hi,
The network performance could be a little different from the CVPR version.
We modified the discriminator architecture a little, so it would lead the generator to a different local optima. I believe you got a better result and you are good to go.
In case you need the very images at submission time, please send me a mail.

**Comment by Git-H2K** [comment]
Thanks :)
